SDL2_LilyEngine: ExampleGame Class Reference
ExampleGame Class Reference
#include <ExampleGame.hpp>
Public Member Functions
ExampleGame (std::string title="This is an Example Game!")
Construct a new Example Game object Sets window title, size, and autorun.
~ExampleGame ()
Frees up ExampleGame resources from memory.
void run () override
The main game loop. Updates clock, checks for events, updates game logic, and renders the screen. Exits if isRunning is false.
bool init () override
bool event (SDL_Event &event) override
void update () override
void render () override
void cleanup () override
Public Member Functions inherited from LilyEngine::BaseGame
BaseGame (const char *title, int width=640, int height=480, bool run_instantly=false)
Construct a BaseGame object, with a given title, window size, and autorun flag. Initializes SDL and its subsystems, creates SDL window and renderer, and sets up LilyEngine systems. If autorun is true, the game will automatically start and run inside the constructor. If you need an exit code for the game, call run() seperately.
virtual ~BaseGame ()=0
Frees your resources with cleanup(), destroys LilyEngine and SDL systems.
SDL_Point getWindowSize ()
Private Attributes
LilyEngine::LTextBox * textbox
Additional Inherited Members
Static Public Member Functions inherited from LilyEngine::BaseGame
static BaseGame * getGame ()
Protected Member Functions inherited from LilyEngine::BaseGame
SDL_Window * getWindow ()
SDL_Renderer * getRenderer ()
TTF_Font * getFont ()
Detailed Description
Definition at line 17 of file ExampleGame.hpp.
Constructor & Destructor Documentation
ExampleGame()
ExampleGame::ExampleGame (std::string title = "This is an Example Game!")
Construct a new Example Game object Sets window title, size, and autorun.
Definition at line 18 of file ExampleGame.cpp.
 : BaseGame(title.c_str(), 640, 480, false)
 {
 }
~ExampleGame()
ExampleGame::~ExampleGame ()
Frees up ExampleGame resources from memory.
Definition at line 61 of file ExampleGame.cpp.
 {
 }
Member Function Documentation
run()
void ExampleGame::run () override virtual
The main game loop. Updates clock, checks for events, updates game logic, and renders the screen. Exits if isRunning is false.
Reimplemented from LilyEngine::BaseGame.
Definition at line 23 of file ExampleGame.cpp.
 {
     BaseGame::run();
 }
Referenced by main().
init()
bool ExampleGame::init () override virtual
Implements LilyEngine::BaseGame.
Definition at line 30 of file ExampleGame.cpp.
 {
     // Load a text box
     textbox = new LilyEngine::LTextBox(getFont(), "Here is some default text!");
     return true;
 }
References LilyEngine::BaseGame::getFont(), and textbox.
event()
bool ExampleGame::event (SDL_Event & event) override virtual
Implements LilyEngine::BaseGame.
Definition at line 37 of file ExampleGame.cpp.
 {
     return false;
 }
update()
void ExampleGame::update () override virtual
Implements LilyEngine::BaseGame.
Definition at line 42 of file ExampleGame.cpp.
 {
 }
render()
void ExampleGame::render () override virtual
Implements LilyEngine::BaseGame.
Definition at line 47 of file ExampleGame.cpp.
 {
     textbox->render(getRenderer());
 }
References LilyEngine::BaseGame::getRenderer(), LilyEngine::LTextBox::render(), and textbox.
cleanup()
void ExampleGame::cleanup () override virtual
Implements LilyEngine::BaseGame.
Definition at line 52 of file ExampleGame.cpp.
 {
     // free resources
     delete textbox;
 }
References textbox.
Member Data Documentation
textbox
LilyEngine::LTextBox* ExampleGame::textbox private
Definition at line 20 of file ExampleGame.hpp.
Referenced by cleanup(), init(), and render().
The documentation for this class was generated from the following files:
include/ExampleGame.hpp
src/ExampleGame.cpp