SDL2_LilyEngine: LilyEngine::LTextBox Class Reference
LilyEngine::LTextBox Class Reference
Creates a Text box message out of a TTF_Font, holds message texture & surface, rect, color, and parent font.
#include <LTextBox.hpp>
Public Member Functions
LTextBox (TTF_Font *font, std::string text, SDL_Color color={ 0xFF, 0xFF, 0xFF })
~LTextBox ()
void setRectCenter ()
Sets the text box to the center of the screen.
void setSize (SDL_Point point)
Shortcut for setSize(width, height).
void setSize (int width, int height)
Sets the size of the text box rect.
SDL_Point getSize ()
gets the position of the text box rect as an SDL_Point.
SDL_Point getSurfaceSize ()
Get's the width and height of the text surface.
void setText (std::string newText)
std::string getText ()
void setColor (SDL_Color newColor)
SDL_Color getColor ()
void setRect (SDL_Rect newBox)
SDL_Rect getRect ()
void setPosition (SDL_Point newPos)
Sets the position of the text box rect.
void setPosition (int x, int y)
Sets the position of the text box rect.
SDL_Point getPosition ()
void setFont (TTF_Font *newFont)
TTF_Font * getFont ()
bool render (SDL_Renderer *renderer)
Private Member Functions
bool create_surface ()
Creates the SDL_Surface from the saved font, text, and color.
bool create_texture (SDL_Renderer *renderer)
Private Attributes
TTF_Font * font
std::string text
SDL_Color color
SDL_Rect box
SDL_Surface * message_surface = nullptr
SDL_Texture * message_texture = nullptr
Detailed Description
Creates a Text box message out of a TTF_Font, holds message texture & surface, rect, color, and parent font.
Definition at line 19 of file LTextBox.hpp.
Constructor & Destructor Documentation
LTextBox()
LilyEngine::LTextBox::LTextBox (TTF_Font * font, std::string text, SDL_Color color = { 0xFF, 0xFF, 0xFF })
Definition at line 18 of file LTextBox.cpp.
     {
         LTextBox::font = font;
         LTextBox::text = text;
         LTextBox::color = color;
         create_surface();
         setRectCenter();
     }
References color, create_surface(), font, setRectCenter(), and text.
~LTextBox()
LilyEngine::LTextBox::~LTextBox ()
Definition at line 29 of file LTextBox.cpp.
     {
         // free our resources
         SDL_FreeSurface(message_surface);
         SDL_DestroyTexture(message_texture);
     }
References message_surface, and message_texture.
Member Function Documentation
setRectCenter()
void LilyEngine::LTextBox::setRectCenter ()
Sets the text box to the center of the screen.
Definition at line 86 of file LTextBox.cpp.
     {
         SDL_Point surf_size = getSurfaceSize();
         SDL_Point win_size = LilyEngine::instance->getWindowSize();
         int bx = (win_size.x / 2) - (surf_size.x / 2);
         int by = (win_size.y / 2) - (surf_size.y / 2);
         SDL_Rect center_rect = SDL_Rect{ bx, by, surf_size.x, surf_size.y };
         setRect(center_rect);
     }
References getSurfaceSize(), LilyEngine::BaseGame::getWindowSize(), LilyEngine::instance, and setRect().
Referenced by LTextBox().
setSize() [1/2]
void LilyEngine::LTextBox::setSize (SDL_Point point)
Shortcut for setSize(width, height).
Parameters
point an SDL_Point with the width and height.
Definition at line 101 of file LTextBox.cpp.
     {
         setSize(point.x, point.y);
     }
setSize() [2/2]
void LilyEngine::LTextBox::setSize (int width, int height)
Sets the size of the text box rect.
Parameters
width new width of the text box.
height new height of the text box.
Definition at line 112 of file LTextBox.cpp.
     {
         SDL_Rect new_rect = getRect();
         new_rect.w = width;
         new_rect.h = height;
         setRect(new_rect);
     }
References getRect(), and setRect().
getSize()
SDL_Point LilyEngine::LTextBox::getSize ()
gets the position of the text box rect as an SDL_Point.
Returns
SDL_Point position of the text box.
Definition at line 125 of file LTextBox.cpp.
     {
         return SDL_Point{box.w, box.h};
     }
References box.
getSurfaceSize()
SDL_Point LilyEngine::LTextBox::getSurfaceSize ()
Get's the width and height of the text surface.
Returns
SDL_Point with width and height of the text surface.
Definition at line 164 of file LTextBox.cpp.
     {
         return SDL_Point{message_surface->w, message_surface->h};
     }
References message_surface.
Referenced by setRectCenter().
setText()
void LilyEngine::LTextBox::setText (std::string newText)
Definition at line 175 of file LTextBox.cpp.
 { text = newText; }
References text.
getText()
std::string LilyEngine::LTextBox::getText ()
Definition at line 176 of file LTextBox.cpp.
 { return text; }
References text.
setColor()
void LilyEngine::LTextBox::setColor (SDL_Color newColor)
Definition at line 178 of file LTextBox.cpp.
 { color = newColor; }
References color.
getColor()
SDL_Color LilyEngine::LTextBox::getColor ()
Definition at line 179 of file LTextBox.cpp.
 { return color; }
References color.
setRect()
void LilyEngine::LTextBox::setRect (SDL_Rect newBox)
Definition at line 181 of file LTextBox.cpp.
 { box = newBox; }
References box.
Referenced by setPosition(), setRectCenter(), and setSize().
getRect()
SDL_Rect LilyEngine::LTextBox::getRect ()
Definition at line 182 of file LTextBox.cpp.
 { return box; }
References box.
Referenced by setPosition(), and setSize().
setPosition() [1/2]
void LilyEngine::LTextBox::setPosition (SDL_Point newPos)
Sets the position of the text box rect.
Parameters
newPos the SDL_Point with the new position.
Definition at line 135 of file LTextBox.cpp.
     {
         setPosition(newPos.x, newPos.y);
     }
setPosition() [2/2]
void LilyEngine::LTextBox::setPosition (int x, int y)
Sets the position of the text box rect.
Parameters
x new x position of the text box.
y new y position of the text box.
Definition at line 146 of file LTextBox.cpp.
     {
         SDL_Rect new_rect = getRect();
         new_rect.x = x;
         new_rect.y = y;
         setRect(new_rect);
     }
References getRect(), and setRect().
getPosition()
SDL_Point LilyEngine::LTextBox::getPosition ()
Definition at line 154 of file LTextBox.cpp.
     {
         return SDL_Point{box.x, box.y};
     }
References box.
setFont()
void LilyEngine::LTextBox::setFont (TTF_Font * newFont)
Definition at line 184 of file LTextBox.cpp.
 { font = newFont; }
References font.
getFont()
TTF_Font * LilyEngine::LTextBox::getFont ()
Definition at line 185 of file LTextBox.cpp.
 { return font; }
References font.
render()
bool LilyEngine::LTextBox::render (SDL_Renderer * renderer)
Definition at line 37 of file LTextBox.cpp.
     {
         // if we need to make the texture,
         if (message_texture == nullptr)
         {
             // give it the renderer here
             bool success = create_texture(renderer);
             if (!success) return false;
         }
         // draw the texture
         SDL_RenderCopy(renderer, message_texture, NULL, &box);
         return true;
     }
References box, create_texture(), and message_texture.
Referenced by ExampleGame::render().
create_surface()
bool LilyEngine::LTextBox::create_surface () private
Creates the SDL_Surface from the saved font, text, and color.
Returns
true if successful, false if not.
Definition at line 57 of file LTextBox.cpp.
     {
         // as TTF_RenderText_Solid could only be used on
         // SDL_Surface then you have to create the surface first
         message_surface = TTF_RenderText_Solid(font, text.c_str(), color);
         if (message_surface == NULL)
         {
             error("TTF_RenderText_Solid failed", TTF);
             return false;
         }
         return true;
     }
References color, error(), font, message_surface, text, and TTF.
Referenced by LTextBox().
create_texture()
bool LilyEngine::LTextBox::create_texture (SDL_Renderer * renderer) private
Definition at line 70 of file LTextBox.cpp.
     {
         // now you can convert it into a texture using the renderer
         message_texture = SDL_CreateTextureFromSurface(renderer, message_surface);
         if (message_texture == NULL) {
             return false;
         }
         else {
             return true;
         }
     }
References message_surface, and message_texture.
Referenced by render().
Member Data Documentation
font
TTF_Font* LilyEngine::LTextBox::font private
Definition at line 23 of file LTextBox.hpp.
Referenced by create_surface(), getFont(), LTextBox(), and setFont().
text
std::string LilyEngine::LTextBox::text private
Definition at line 24 of file LTextBox.hpp.
Referenced by create_surface(), getText(), LTextBox(), and setText().
color
SDL_Color LilyEngine::LTextBox::color private
Definition at line 25 of file LTextBox.hpp.
Referenced by create_surface(), getColor(), LTextBox(), and setColor().
box
SDL_Rect LilyEngine::LTextBox::box private
Definition at line 27 of file LTextBox.hpp.
Referenced by getPosition(), getRect(), getSize(), render(), and setRect().
message_surface
SDL_Surface* LilyEngine::LTextBox::message_surface = nullptr private
Definition at line 29 of file LTextBox.hpp.
Referenced by create_surface(), create_texture(), getSurfaceSize(), and ~LTextBox().
message_texture
SDL_Texture* LilyEngine::LTextBox::message_texture = nullptr private
Definition at line 30 of file LTextBox.hpp.
Referenced by create_texture(), render(), and ~LTextBox().
The documentation for this class was generated from the following files:
include/LTextBox.hpp
src/LTextBox.cpp