SDL2_LilyEngine: LilyEngine::BaseGame Class Reference
LilyEngine::BaseGame Class Reference abstract
Abstract base class for all games made with SDL_LilyEngine. Inherit for your own game, and implement the virtual functions.
#include <BaseGame.hpp>
Public Member Functions
BaseGame (const char *title, int width=640, int height=480, bool run_instantly=false)
Construct a BaseGame object, with a given title, window size, and autorun flag. Initializes SDL and its subsystems, creates SDL window and renderer, and sets up LilyEngine systems. If autorun is true, the game will automatically start and run inside the constructor. If you need an exit code for the game, call run() seperately.
virtual ~BaseGame ()=0
Frees your resources with cleanup(), destroys LilyEngine and SDL systems.
virtual void run ()
The main game loop. Updates clock, checks for events, updates game logic, and renders the screen. Exits if isRunning is false.
SDL_Point getWindowSize ()
Static Public Member Functions
static BaseGame * getGame ()
Protected Member Functions
virtual bool init ()=0
virtual bool event (SDL_Event &event)=0
virtual void update ()=0
virtual void render ()=0
virtual void cleanup ()=0
SDL_Window * getWindow ()
SDL_Renderer * getRenderer ()
TTF_Font * getFont ()
Private Member Functions
bool init_sdl_systems (const char *title, int xpos=SDL_WINDOWPOS_CENTERED, int ypos=SDL_WINDOWPOS_CENTERED, int width=640, int height=480, bool fullscreen=false, Uint32 sdl_init_flags=SDL_INIT_EVERYTHING)
Private internal method to initialize SDL systems.
bool load_engine_resources ()
Loads internal engine resources, like a default font, etc.
bool engine_handle_event (SDL_Event &event)
Events that the game engine needs to handle.
void engine_update ()
Updates engine logic.
void engine_render ()
void engine_clean ()
Frees engine resources & systems.
Private Attributes
int win_width
int win_height
SDL_Window * window
SDL_Renderer * renderer
TTF_Font * font
LilyEngine::Clock clock {}
Detailed Description
Abstract base class for all games made with SDL_LilyEngine. Inherit for your own game, and implement the virtual functions.
Definition at line 37 of file BaseGame.hpp.
Constructor & Destructor Documentation
BaseGame()
LilyEngine::BaseGame::BaseGame (const char * title, int width = 640, int height = 480, bool autorun = false)
Construct a BaseGame object, with a given title, window size, and autorun flag. Initializes SDL and its subsystems, creates SDL window and renderer, and sets up LilyEngine systems. If autorun is true, the game will automatically start and run inside the constructor. If you need an exit code for the game, call run() seperately.
Parameters
title The title of the window.
width width of the window.
height height of the window.
autorun Whether or not to automatically run the game.
Definition at line 32 of file BaseGame.cpp.
     {
         bool systems_initialized = init_sdl_systems(title, SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED, width, height);
         if (!systems_initialized)
         {
             error("SDL systems could not be initialized!", SDL);
             return;
         }
         printf("SDL systems initialized!");
         bool resources_initialized = load_engine_resources();
         if (!resources_initialized)
         {
             error("Resources could not be initialized!", SDL);
             return;
         }
         printf("Resources initialized!");
         SDL_GetWindowSize(window, &win_width, &win_height);
         clock.running = true;   // Start the game clock, needed to run the game.
         instance = this;        // Set the game pointer to this game.
         std::cout << "Engine Initialized!" << std::endl;
         if(autorun) run();
     }
References clock, error(), init_sdl_systems(), LilyEngine::instance, load_engine_resources(), run(), LilyEngine::Clock::running, SDL, win_height, win_width, and window.
~BaseGame()
LilyEngine::BaseGame::~BaseGame () pure virtual
Frees your resources with cleanup(), destroys LilyEngine and SDL systems.
Definition at line 100 of file BaseGame.cpp.
     {
         // Clean up system objects.
         SDL_DestroyRenderer(renderer);
         SDL_DestroyWindow(window);
         // Quit SDL subsystems.
         TTF_Quit();
         SDL_Quit();
         //delete this_game; // Delete the game pointer.
     }
References renderer, and window.
Member Function Documentation
run()
void LilyEngine::BaseGame::run () virtual
The main game loop. Updates clock, checks for events, updates game logic, and renders the screen. Exits if isRunning is false.
Reimplemented in ExampleGame.
Definition at line 62 of file BaseGame.cpp.
     {
         bool game_initialized = init();
         if (!game_initialized)
         {
             error("Game init() failed!", SDL);
             return;
         }
         printf("Game initialized!");
         std::cout << "Running game..." << std::endl;
         SDL_Event _event;
         while (clock.running)
         {
             while (SDL_PollEvent(&_event))
             {
                 if(!engine_handle_event(_event)) {
                     event(_event);
                 }
             }
             engine_update();
             update();
             SDL_SetRenderDrawColor(renderer, clock.ticks, clock.ticks, clock.ticks, SDL_ALPHA_OPAQUE);
             SDL_RenderClear(renderer);
             engine_render();
             render();
             SDL_RenderPresent(renderer);
             clock.tick();
         }
     }
References clock, engine_handle_event(), engine_render(), engine_update(), error(), event(), init(), render(), renderer, LilyEngine::Clock::running, SDL, LilyEngine::Clock::tick(), LilyEngine::Clock::ticks, and update().
Referenced by BaseGame().
getWindowSize()
SDL_Point LilyEngine::BaseGame::getWindowSize ()
Definition at line 114 of file BaseGame.cpp.
     {
         return SDL_Point{ win_width, win_height };
     }
References win_height, and win_width.
Referenced by LilyEngine::LTextBox::setRectCenter().
getGame()
BaseGame * LilyEngine::BaseGame::getGame () static
Definition at line 119 of file BaseGame.cpp.
     {
         return instance;
     }
References LilyEngine::instance.
init()
virtual bool LilyEngine::BaseGame::init () protected pure virtual
Implemented in ExampleGame.
Referenced by run().
event()
virtual bool LilyEngine::BaseGame::event (SDL_Event & event) protected pure virtual
Implemented in ExampleGame.
Referenced by run().
update()
virtual void LilyEngine::BaseGame::update () protected pure virtual
Implemented in ExampleGame.
Referenced by run().
render()
virtual void LilyEngine::BaseGame::render () protected pure virtual
Implemented in ExampleGame.
Referenced by run().
cleanup()
virtual void LilyEngine::BaseGame::cleanup () protected pure virtual
Implemented in ExampleGame.
getWindow()
SDL_Window * LilyEngine::BaseGame::getWindow () protected
Definition at line 124 of file BaseGame.cpp.
     {
         return window;
     }
References window.
getRenderer()
SDL_Renderer * LilyEngine::BaseGame::getRenderer () protected
Definition at line 129 of file BaseGame.cpp.
     {
         return renderer;
     }
References renderer.
Referenced by ExampleGame::render().
getFont()
TTF_Font * LilyEngine::BaseGame::getFont () protected
Definition at line 134 of file BaseGame.cpp.
     {
         return font;
     }
References font.
Referenced by ExampleGame::init().
init_sdl_systems()
bool LilyEngine::BaseGame::init_sdl_systems (const char * title, int xpos = SDL_WINDOWPOS_CENTERED, int ypos = SDL_WINDOWPOS_CENTERED, int width = 640, int height = 480, bool fullscreen = false, Uint32 sdl_init_flags = SDL_INIT_EVERYTHING) private
Private internal method to initialize SDL systems.
Parameters
title the initial title of the window.
xpos window x position (defaults to center)
ypos window y position (defaults to center)
width window width (defaults to 640)
height window height (defaults to 480)
fullscreen window fullscreen flag (defaults to false)
sdl_init_flags flags to pass to SDL_Init()
Returns
true if SDL and subsystems was initialized successfully, false otherwise.
Definition at line 158 of file BaseGame.cpp.
     {
         bool sdl_initialized = SDL_Init(sdl_init_flags);
         if(sdl_initialized != 0)
         {
             std::cout << "SDL could not initialize! SDL Error: " << SDL_GetError() << std::endl;
             return false;
         }
         bool ttf_initialized = TTF_Init();
         if(ttf_initialized == -1)
         {
             std::cout << "SDL_TTF could not initialize! SDL Error: " << TTF_GetError() << std::endl;
             return false;
         }
         window = SDL_CreateWindow(title, xpos, ypos, width, height, 0);
         if(window == NULL)
         {
             std::cout << "SDL could not make a window! SDL Error: " << SDL_GetError() << std::endl;
             return false;
         }
         renderer = SDL_CreateRenderer(window, -1, SDL_RENDERER_PRESENTVSYNC | SDL_RENDERER_ACCELERATED);
         if(window == NULL)
         {
             std::cout << "SDL could not make a renderer! SDL Error: " << SDL_GetError() << std::endl;
             return false;
         }
         return true;
     }
References renderer, and window.
Referenced by BaseGame().
load_engine_resources()
bool LilyEngine::BaseGame::load_engine_resources () private
Loads internal engine resources, like a default font, etc.
Returns
true if resources were loaded successfully, false otherwise.
Definition at line 195 of file BaseGame.cpp.
     {
         // Load a font
         std::string font_path = "resources/712_serif.ttf";
         font = TTF_OpenFont(font_path.c_str(), 32);
         if (font == NULL)
         {
             error("Unable to load font \"" + font_path + "\".", TTF);
             return false;
         }
         return true;
     }
References error(), font, and TTF.
Referenced by BaseGame().
engine_handle_event()
bool LilyEngine::BaseGame::engine_handle_event (SDL_Event & _event) private
Events that the game engine needs to handle.
Returns
true if the event was handled, false otherwise and needs to be handled by the game implementation.
Definition at line 214 of file BaseGame.cpp.
     {
         switch (_event.type)
         {
         case SDL_QUIT:
             clock.running = false;
             return true;
         case SDL_KEYDOWN:
             if (_event.key.keysym.sym == SDLK_ESCAPE)
             {
                 clock.running = false;
             }
             return true;
         }
         // event not handled
         return false;
     }
References clock, and LilyEngine::Clock::running.
Referenced by run().
engine_update()
void LilyEngine::BaseGame::engine_update () private
Updates engine logic.
Definition at line 236 of file BaseGame.cpp.
     {
     }
Referenced by run().
engine_render()
void LilyEngine::BaseGame::engine_render () private
Definition at line 241 of file BaseGame.cpp.
     {
         //SDL_RenderPresent(renderer);
     }
Referenced by run().
engine_clean()
void LilyEngine::BaseGame::engine_clean () private
Frees engine resources & systems.
Definition at line 249 of file BaseGame.cpp.
     {
         TTF_CloseFont(font);
         // free SDL subsystems
         SDL_DestroyWindow(window);
         SDL_DestroyRenderer(renderer);
         SDL_Quit();
     }
References font, renderer, and window.
Member Data Documentation
win_width
int LilyEngine::BaseGame::win_width private
Definition at line 71 of file BaseGame.hpp.
Referenced by BaseGame(), and getWindowSize().
win_height
int LilyEngine::BaseGame::win_height private
Definition at line 71 of file BaseGame.hpp.
Referenced by BaseGame(), and getWindowSize().
window
SDL_Window* LilyEngine::BaseGame::window private
Definition at line 72 of file BaseGame.hpp.
Referenced by BaseGame(), engine_clean(), getWindow(), init_sdl_systems(), and ~BaseGame().
renderer
SDL_Renderer* LilyEngine::BaseGame::renderer private
Definition at line 73 of file BaseGame.hpp.
Referenced by engine_clean(), getRenderer(), init_sdl_systems(), run(), and ~BaseGame().
font
TTF_Font* LilyEngine::BaseGame::font private
Definition at line 74 of file BaseGame.hpp.
Referenced by engine_clean(), getFont(), and load_engine_resources().
clock
LilyEngine::Clock LilyEngine::BaseGame::clock {} private
Definition at line 75 of file BaseGame.hpp.
Referenced by BaseGame(), engine_handle_event(), and run().
The documentation for this class was generated from the following files:
include/BaseGame.hpp
src/BaseGame.cpp