SDL2_LilyEngine: src/SDLError.cpp File Reference
SDLError.cpp File Reference
#include "SDLError.hpp"
#include <string>
Functions
void error (std::string message, ErrorType error_type)
report an error to the console, with relevant SDL module error, and pause the console to read.
Function Documentation
error()
void error (std::string message, ErrorType error_type)
report an error to the console, with relevant SDL module error, and pause the console to read.
Parameters
message Your message of the error.
error_type Optional, specify ErrorType SDL or TTF to report error from that module. Defaults to NoneError.
Definition at line 14 of file SDLError.cpp.
 {
     std::string sdl_message;
     switch (error_type) {
     case SDL:
         sdl_message = SDL_GetError();
         break;
     case TTF:
         sdl_message = TTF_GetError();
         break;
     default:
         sdl_message = "Unknown";
     }
     std::cout << message << std::endl;
     if (error_type != NoneError)
         std::cout << errorString[error_type] << " Error: " << sdl_message << std::endl;
     system("pause");
 }
References errorString, NoneError, SDL, and TTF.
Referenced by LilyEngine::BaseGame::BaseGame(), LilyEngine::LTextBox::create_surface(), LilyEngine::BaseGame::load_engine_resources(), and LilyEngine::BaseGame::run().