SDL2_LilyEngine: include/SDLError.hpp File Reference
SDLError.hpp File Reference
#include <SDL.h>
#include <SDL_ttf.h>
#include <iostream>
#include <string>
#include <map>
Macros
#define _SDL2_LILYENGINE_ERROR_HPP_
Enumerations
enum ErrorType { NoneError , SDL , TTF }
Enumeration of all SDL error types, NoneError being 0.
Functions
void error (std::string message, ErrorType error_type=NoneError)
report an error to the console, with relevant SDL module error, and pause the console to read.
Variables
static std::map< ErrorType, std::string > errorString
Map of ErrorType to display string.
Macro Definition Documentation
_SDL2_LILYENGINE_ERROR_HPP_
#define _SDL2_LILYENGINE_ERROR_HPP_
Definition at line 8 of file SDLError.hpp.
Enumeration Type Documentation
ErrorType
enum ErrorType
Enumeration of all SDL error types, NoneError being 0.
Enumerator
NoneError
SDL
TTF
Definition at line 21 of file SDLError.hpp.
 { NoneError, SDL, TTF };
Function Documentation
error()
void error (std::string message, ErrorType error_type)
report an error to the console, with relevant SDL module error, and pause the console to read.
Parameters
message Your message of the error.
error_type Optional, specify ErrorType SDL or TTF to report error from that module. Defaults to NoneError.
Definition at line 14 of file SDLError.cpp.
 {
     std::string sdl_message;
     switch (error_type) {
     case SDL:
         sdl_message = SDL_GetError();
         break;
     case TTF:
         sdl_message = TTF_GetError();
         break;
     default:
         sdl_message = "Unknown";
     }
     std::cout << message << std::endl;
     if (error_type != NoneError)
         std::cout << errorString[error_type] << " Error: " << sdl_message << std::endl;
     system("pause");
 }
References errorString, NoneError, SDL, and TTF.
Referenced by LilyEngine::BaseGame::BaseGame(), LilyEngine::LTextBox::create_surface(), LilyEngine::BaseGame::load_engine_resources(), and LilyEngine::BaseGame::run().
Variable Documentation
errorString
std::map< ErrorType, std::string > errorString static
Initial value:
= {
   {NoneError, "None"},
   {SDL, "SDL"},
   {TTF, "SDL_TTF"}
}
Map of ErrorType to display string.
Definition at line 26 of file SDLError.hpp.
Referenced by error().