SDL2_LilyEngine: LilyEngine::Clock Struct Reference
LilyEngine::Clock Struct Reference
Clock struct to keep track of game time, delta time, ticks, framerate, vsync, etc.
#include <Clock.hpp>
Public Member Functions
void tick (bool isVSyncOn=true, float fps=-1)
This will update game time variables based on SDL_GetTicks(), then delay based on desired FPS. isVSyncOn should be set to true if SDL_RENDERER_PRESENTVSYNC was passed to the renderer. fps should be only set if vsync is false. -1 is unlimited.
Public Attributes
bool running = false
Uint64 last_tick_time = 0
float delta = 0
float delta_ms = 0
int ticks = 0
float seconds = 0
int minutes = 0
int hours = 0
Private Member Functions
Uint64 get_time_from_SDL ()
Get the time from SDL using system-specific high-resolution timer.
float calculate_delta (Uint64 new_tick_time)
Calculate the delta time from last tick using new (current) tick time, last tick time, and dividing by performance frequency to get delta seconds.
void update_clocks ()
Update seconds, minutes, and hours after delta has been calculated.
void cap_framerate (float desired_fps)
Halt program execution according to desired target FPS.
Detailed Description
Clock struct to keep track of game time, delta time, ticks, framerate, vsync, etc.
Definition at line 19 of file Clock.hpp.
Member Function Documentation
tick()
void LilyEngine::Clock::tick (bool isVSyncOn = true, float fps = -1) inline
This will update game time variables based on SDL_GetTicks(), then delay based on desired FPS. isVSyncOn should be set to true if SDL_RENDERER_PRESENTVSYNC was passed to the renderer. fps should be only set if vsync is false. -1 is unlimited.
Parameters
isVSyncOn tell tick() if hardware vsync is on.
fps The desired frame rate.
Definition at line 42 of file Clock.hpp.
         {
             Uint64 tick_time = get_time_from_SDL(); // update our tick time from SDL
             delta = calculate_delta(tick_time);     // get delta time from tick
             delta_ms = delta * 1000.0f;             // convert to milliseconds
             update_clocks();
             if (!isVSyncOn) // if hardware vsync is off and we need to cap framerate...
             {
                 cap_framerate(fps);
             }
             /*
             * Set up for next frame (tick)
             */
             ticks++;                        // increase ticks (essentially frame count)
             last_tick_time = tick_time;     // save tick_time into last_tick_time for the next tick() call
         }
References calculate_delta(), cap_framerate(), delta, delta_ms, get_time_from_SDL(), last_tick_time, ticks, and update_clocks().
Referenced by LilyEngine::BaseGame::run().
get_time_from_SDL()
Uint64 LilyEngine::Clock::get_time_from_SDL () inline private
Get the time from SDL using system-specific high-resolution timer.
Returns
Uint64 SDL_GetPerformanceCounter()
Definition at line 68 of file Clock.hpp.
         {
             return SDL_GetPerformanceCounter();
         }
Referenced by tick().
calculate_delta()
float LilyEngine::Clock::calculate_delta (Uint64 new_tick_time) inline private
Calculate the delta time from last tick using new (current) tick time, last tick time, and dividing by performance frequency to get delta seconds.
Parameters
new_tick_time Should be from get_time_from_SDL()
Returns
float Delta time in seconds.
Definition at line 80 of file Clock.hpp.
         {
             if (last_tick_time != 0)
             {
                 float _elapsed = new_tick_time - last_tick_time;                // get elapsed time since last tick()
                 // SDL_GetPerformanceCounter() is system specific; we must divide by frequency per second to get our delta time.
                 return _elapsed / (float)SDL_GetPerformanceFrequency(); // this is in seconds
             }
             else {
                 return 0;
             }
         }
References last_tick_time.
Referenced by tick().
update_clocks()
void LilyEngine::Clock::update_clocks () inline private
Update seconds, minutes, and hours after delta has been calculated.
Definition at line 96 of file Clock.hpp.
         {
             seconds += delta;                       // add delta time to our seconds counter
             minutes = (int)floor(seconds / 60.0);   // get minutes since startup (int)
             hours = (int)floor(seconds / 3600.0);   // get hours since startup (int)
             //verbose_debug(println("Game Time: " << seconds << "s, " << minutes << "m, " << hours << "h."));
             //verbose_debug(print("delta: " << delta));
         }
References delta, hours, minutes, and seconds.
Referenced by tick().
cap_framerate()
void LilyEngine::Clock::cap_framerate (float desired_fps) inline private
Halt program execution according to desired target FPS.
Parameters
desired_fps target FPS to cap framerate at.
Definition at line 111 of file Clock.hpp.
         {
             float desired_delta = (1.0f / desired_fps) * 1000.0f;   // calculate desired ms between frames from desired FPS
             if (desired_delta - delta > 0)  // if less than desired ms has passed...we must wait
             {
                 float delay = std::max(desired_delta - delta, 0.0f);    // calculate the time we should delay
                 //verbose_debug(println(" TRYING TO DELAY: " << desired_delta << " - " << delta << " = " << delay));
                 SDL_Delay(delay);       // delay
             }
         }
References delta.
Referenced by tick().
Member Data Documentation
running
bool LilyEngine::Clock::running = false
Definition at line 22 of file Clock.hpp.
Referenced by LilyEngine::BaseGame::BaseGame(), LilyEngine::BaseGame::engine_handle_event(), and LilyEngine::BaseGame::run().
last_tick_time
Uint64 LilyEngine::Clock::last_tick_time = 0
Definition at line 25 of file Clock.hpp.
Referenced by calculate_delta(), and tick().
delta
float LilyEngine::Clock::delta = 0
Definition at line 26 of file Clock.hpp.
Referenced by cap_framerate(), tick(), and update_clocks().
delta_ms
float LilyEngine::Clock::delta_ms = 0
Definition at line 27 of file Clock.hpp.
Referenced by tick().
ticks
int LilyEngine::Clock::ticks = 0
Definition at line 28 of file Clock.hpp.
Referenced by LilyEngine::BaseGame::run(), and tick().
seconds
float LilyEngine::Clock::seconds = 0
Definition at line 30 of file Clock.hpp.
Referenced by update_clocks().
minutes
int LilyEngine::Clock::minutes = 0
Definition at line 31 of file Clock.hpp.
Referenced by update_clocks().
hours
int LilyEngine::Clock::hours = 0
Definition at line 32 of file Clock.hpp.
Referenced by update_clocks().
The documentation for this struct was generated from the following file:
include/Clock.hpp